version: "3"

services:
  nginx:
    container_name: "nginx"
    depends_on:
      - app
    restart: always
    build:
      dockerfile: "Dockerfile"
      context: "./nginx"
    ports:
      - "80:80"

  app:
    env_file: "./app/.env"
    container_name: "server"
    build:
      context: "./app"
      dockerfile: "./Dockerfile"
    image: node:latest-alpine
    restart: unless-stopped
    ports:
      - "3010:3010"
    command: "npm start"
